version: '3.8'

services:
  synap-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "7001:7001"
    environment:
      - NODE_ENV=production
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - WEB_OWNER=${WEB_OWNER}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

